void revery_alert_win32(void *pWin, const char* szMessage);
void* revery_getIconHandle_win32();
void revery_setIconProgress_win32(void *win, void *ih, float progress);
void revery_setIconProgressIndeterminate_win32(void *win, void *ih);
void revery_hideIconProgress_win32(void *win, void *ih);
int revery_openURL_win32(const char *url_string);
value revery_assign_menu_win32(void *pWindow, value vMenu);
value revery_create_sub_menu_win32(void);
value revery_create_menu_win32(void);
value revery_menu_insert_node_string_win32(value vMenu, int position, int uid, const char *pMessage);
value revery_menu_delete_node_string_win32(value vMenu, int position);
value revery_menu_item_configure_instance_label_win32(value vParent, int position, const char *pMessage);
